### ISSUE TITLE
Calling prop_or may crash in `return o[name]` of prop.py

### ISSUE THREAD

**Issue by mnieber** [slavaGanzin/ramda.py#9]
ramda==0.6.0

This problem happens under the following circumstances:

- you call `prop_or` on a Python object that is not a dictionary
- the property does not exist on this python object

In this case ramda will try to treat it as a dictionary and call `o[name]`. In itself that is correct - because `o` might be a dictionary - but the code should not crash if `o` is *not* a dictionary.

**Comment by slavaGanzin** [comment]
Maarten, thanks for your rigorousness!
Everybody expects that ramda.py should work as ramda.js. 

Even I was frustrated by all this raises that this library gives you from time to time, but I always forget to address this. Now it should be fixed with https://github.com/slavaGanzin/ramda.py/commit/006de162bc3ed02b92a17409ecd90a52ba2fd650. Please review

If you find something non-strict, as in this case, fill free to create an issue. But better demonstrate with a code: functional libraries to abstract and code is always specific. 

fixes [published in 0.6.1](https://pypi.org/project/ramda/0.6.1/)

Thanks!
